guazi:
  mall:
    mybatis:
      sharding:
        master-datasources: master0,master1,master2,master3
        slave-datasources: slave0,slave1,slave2,slave3
        mapper-base-package: shardingXml/sqlmap/*.xml
        mapper-config: shardingXml/sql-map-config.xml
sharding:
  jdbc:
    datasource:
      names: master0,master1,master2,master3,slave0,slave1,slave2,slave3
      master0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://lixiaoxin.site:3306/db0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username:
        password:
      master1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://lixiaoxin.site:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username:
        password:
      master2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://lixiaoxin.site:3306/db2?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username:
        password:
      master3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://lixiaoxin.site:3306/db3?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username:
        password:
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://lixiaoxin.site:3306/db0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username:
        password:
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://lixiaoxin.site:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username:
        password:
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://lixiaoxin.site:3306/db2?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username:
        password:
      slave3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://lixiaoxin.site:3306/db3?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username:
        password:
    config:
      props:
        sql:
          show: false #show sql : true
      sharding:
        master: #主从分离 主表主库
          tables:
            tb_item:
              actual-data-nodes: master0.tb_item$->{0..3}
              table-strategy:
                standard:
                  sharding-column: value
                  precise-algorithm-class-name: com.lxx.demo.shardingjdbc.config.ItemTableSharding
            tb_user: #分库分表可以同时进行
              actual-data-nodes: master$->{0..3}.tb_user
              database-strategy:
                standard:
                  sharding-column: userid
                  precise-algorithm-class-name: com.lxx.demo.shardingjdbc.config.UserDataBaseSharding
        slave: #主从分离 从表 从库
          tables:
            tb_item: #逻辑表名
              actual-data-nodes: slave0.tb_item$->{0..3}
              table-strategy:
                standard:
                  sharding-column: value
                  precise-algorithm-class-name: com.lxx.demo.shardingjdbc.config.ItemTableSharding
            tb_user: #逻辑表名
              actual-data-nodes: slave$->{0..3}.tb_user
              database-strategy:
                standard:
                  sharding-column: userid
                  precise-algorithm-class-name: com.lxx.demo.shardingjdbc.config.UserDataBaseSharding
